version: '1'
services:
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: test123
            MYSQL_USER: test
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: PlotCAD
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
